# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3097bdfbe11ef7a009002f2f6b22321be8c68775a3f5b2c5e504873b7eb2da0e4e35e8593abb9652da5c655b6d1afa47daadfe1c31f4669c331a5e1252fe3d3

test:
  secret_key_base: 96a652b3c3a73db329fb81d7cba921c68b8dfa1efa9a7fc4b388483ccdd17e496cf18ee4bde4000bf9f54222d8e7b3360ed472d58ca68d2b108d415787b28935

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
